language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.10
  - 0.11
script: 
  - "node samples/downloadSample.js"
  - "node samples/usageSample-options.js"
  - "node samples/usageSample.js"
  - "node src/cloud-pipe.js"
notifications:
  email: dev@totendev.com
  irc:
    channels:
      - "irc.freenode.org#TotenDev"
